# {{snake_name}}.mojo
"""
{{name}} layer implementation.

Auto-generated by scripts/generators/generate_layer.py
"""

from shared.nn import Module
from shared.core import ExTensor


struct {{name}}(Module):
    """{{name}} layer.

    A custom neural network layer.
    """

{{member_vars}}
    # TODO: Add trainable parameters as needed
    # var weight: ExTensor
    # var bias: ExTensor

    fn __init__(out self{{init_params}}):
        """Initialize {{name}}.

        Args:
{{init_docs}}
        """
{{member_inits}}
        # TODO: Initialize trainable parameters

    fn forward(self, {{forward_args}}) -> ExTensor:
        """Forward pass through the layer.

        Args:
{{forward_docs}}

        Returns:
            Output tensor
        """
        # TODO: Implement forward computation
        var x = {{first_input}}

        return x

    fn parameters(self) -> List[ExTensor]:
        """Get trainable parameters.

        Returns:
            List of parameter tensors
        """
        var params = List[ExTensor]()
        # TODO: Collect trainable parameters
        return params
