# {{snake_name}}.mojo
"""
{{name}} model for {{model_type}}.

Auto-generated by scripts/generators/generate_model.py
"""

from shared.nn import Module, {{imports}}
from shared.core import ExTensor


struct {{name}}(Module):
    """{{name}} {{model_type}} model.

    A neural network for {{model_type}} tasks.
    """

{{layer_declarations}}

    fn __init__(out self, num_classes: Int = {{num_classes}}):
        """Initialize {{name}}.

        Args:
            num_classes: Number of output classes (default: {{num_classes}})
        """
{{layer_initializations}}

    fn forward(self, input: ExTensor) -> ExTensor:
        """Forward pass through the network.

        Args:
            input: Input tensor

        Returns:
            Output tensor
        """
        var x = input

{{forward_pass}}

        return x

    fn parameters(self) -> List[ExTensor]:
        """Get all trainable parameters.

        Returns:
            List of parameter tensors
        """
        var params = List[ExTensor]()
{{parameter_collection}}
        return params
